# Generated by Django 4.0.2 on 2022-04-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('waiting', 'waiting'), ('confirmed', 'confirmed'), ('apologized', 'apologized')], default='pending', max_length=300),
        ),
    ]
