# Generated by Django 4.0.2 on 2022-04-18 23:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_invitation_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='reference',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
