# Generated by Django 4.0.2 on 2022-05-21 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bride',
            field=models.CharField(blank=True, default='none', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='groom',
            field=models.CharField(blank=True, default='none', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='none', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=500, null=True),
        ),
    ]
