# Generated by Django 4.0.2 on 2022-07-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_event_bride_event_date_event_groom_event_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
