# Generated by Django 4.0.2 on 2022-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_event_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bride',
        ),
        migrations.RemoveField(
            model_name='event',
            name='groom',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
